### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dkoller** [jeffhain/jadecy#1]
Hey there,

do you have any performance measurements? Or expirience you can share?
I work in a project with a rather big code base (around 4 Mio lines) and will maybe try your nice tool.

best regards from zurich
daniel

**Comment by jeffhain** [comment]
Hi.

Sorry for the delay (!), I rarely check this project, you better just send me a mail.
No, I don't have any performance measurement, other than what is done by AllPerfs.main(...).

My experience by working with large lib directories, is that a lot of time is spent parsing the jars to build up the graph structure, then the algorithms run relatively fast (no particular slowness except due to their O(f(n)) "complexity"), so instead of running from command line every time, it's better to use the API from some code, parse classes once, and then do all the computations you want.

To speed things up, once parsing is done, you can run different computations in different threads (new in-memory work structures are created every time, from the internal reference graph created from parsing).
